### ISSUE TITLE
babel-core@^6.0.0 is not installed

### ISSUE THREAD

**Issue by andfinally** [humanmade/liveblog#23]
After running `npm install` I see the error

`UNMET PEER DEPENDENCY babel-core@^6.0.0`

in the command line, and when I start the local server and try to view Liveblog in the browser I see the warning "If you're seeing this, you're doing it wrong!"

When I run `npm install  babel-core@^6.0.0` and start the server again the app appears OK.

**Comment by joehoyle** [comment]
@andfinally are you viewing it at `http://localhost:3000` or via the `file://` url? Do you have any errors in the Browser Console? The babel-core should just be a warning

**Comment by andfinally** [comment]
Hi @joehoyle yes, I get 

`Uncaught Error: Cannot find module "./index"
    at webpackMissingModule (webpack:///multi_main?:5:42)
    at eval (webpack:///multi_main?:5:88)
    at Object.<anonymous> (http://localhost:3000/dist/bundle.js:584:2)
    at __webpack_require__ (http://localhost:3000/dist/bundle.js:554:30)
    at http://localhost:3000/dist/bundle.js:577:37
    at http://localhost:3000/dist/bundle.js:580:10` 

from `webpack:///multi_main?:5` and

`Cannot find module 'babel-core' @ multi main` 

from `client:75`. Console and shell screenshots attached.

![image](https://cloud.githubusercontent.com/assets/1647564/20313571/3e503568-ab4f-11e6-8fba-7ebadbf3067a.png)

![image](https://cloud.githubusercontent.com/assets/1647564/20313597/52ea1b74-ab4f-11e6-9238-d1aed3cbe129.png)

**Comment by joemcgill** [comment]
I ran into this same issue when trying to set up the app. Adding babel-core to the devDependency list fixed the issue. It's possible that someone might not see this warning if they have babel-core installed globally.

**Comment by rmccue** [comment]
Should be fixed now!
